### ISSUE TITLE
When registering new account with contact results in Error unmarshaling body JSON

### ISSUE THREAD

**Issue by Skorpeo** [letsencrypt/pebble#129]
When I try to register a new account with contact in the payload it results in a `malformed request` error `Error unmarshaling body JSON`.  If contact field is left out then it works.  Limited research seems to indicate this is perhaps some sort of a Go issue?  [Link to error in source](https://github.com/letsencrypt/pebble/blob/c5ebb21149b2675ae3f0a5a4a3aaef418fa16dc3/wfe/wfe.go#L693)

**Comment by cpu** [comment]
@Skorpeo What is the JSON request body you are sending?

**Comment by Skorpeo** [comment]
I just figured out the issue.  Contact has to come first.  I had  
```
payload = {"termsOfServiceAgreed": True,
"contact": ["mailto:test@test.com"]}
```
Now I tried with this and it works:
```
payload = {"contact": ["mailto:test@test.com"],
               "termsOfServiceAgreed": True}
```

**Comment by cpu** [comment]
> I just figured out the issue. Contact has to come first.

Hmmmm. I don't think that's the true cause of the problem you experienced. The Go JSON package being used doesn't care about the order of keys in an object.

I'm glad you were able to make progress either way. I suspect that the original problem was caused by sending JSON that doesn't match the schema of the struct it is being unmarshaled into (e.g. something like `contact: "test@test.com"` instead of `contact: ["test@test.com"]`.

**Comment by Skorpeo** [comment]
you may be right not sure what happened, I spent a lot of time with various permutations but now it works and I can't reproduce the error so it was probably my error or I'm just losing my mind...

**Comment by cpu** [comment]
> you may be right not sure what happened, I spent a lot of time with various permutations but now it works and I can't reproduce the error so it was probably my error or I'm just losing my mind...

:laughing: We've all been there. Happy to hear everything is working now.
