### ISSUE TITLE
POST-as-GET fails with malformedRequest

### ISSUE THREAD

**Issue by shred** [letsencrypt/pebble#167]
I am trying to read the current state of an authorization by sending a POST-as-GET request to e.g. `https://localhost:14000/authZ/Xn3qYREpJjrDo7QcGL4hoPK2YbixtF6LUeiZoaIgk3s`. As specified in the draft, the payload is an empty string.

Instead of returning the authorization, Pebble returns a 400 Bad Request with the following problem:
```
{
  "type":"urn:ietf:params:acme:error:malformedRequest",
  "detail":"Malformed authorization update: unexpected end of JSON input",
  "status":400
}
```

**Comment by eggsampler** [comment]
I'm getting the same problem too. After a little investigating I believe it's due to the way jose.v2 decodes the payload, specifically this:

https://github.com/square/go-jose/blob/ef984e69dd356202fd4e4910d4d9c24468bdf0b8/encoding.go#L147-L149

It appears to not differentiate between a missing payload or an empty payload which causes the nil check in pebble to always return false, and thus postAsGet being false:

https://github.com/letsencrypt/pebble/blob/b09dc60e31611024b0e856f7633cd64aa77a707c/wfe/wfe.go#L646

Which then means the requests are being interpreted as a POST not POST-AS-GET, and so it's attempting to parse a non-existent JSON body.

**Comment by cpu** [comment]
This is exactly why I was opposed to using the empty body as the indicator of a POST-as-GET. It's very clear that it causes implementation headaches. 

I will revert https://github.com/letsencrypt/pebble/pull/162/commits/7da91f1b59f16837aaa74b1e1aeb5b9160e38253

Biting my tongue to avoid any more comments about the state of the protocol based on this late breaking IESG feedback..........................................

**Comment by cpu** [comment]
https://github.com/letsencrypt/pebble/pull/168

**Comment by felixfontein** [comment]
As expected, it works again for my implementation! \o/
