### ISSUE TITLE
How can a client get the revocation status of a certificate?

### ISSUE THREAD

**Issue by dxjones** [letsencrypt/pebble#177]
I am developing an ACME client in Go and using Pebble for testing, and I have successfully created accounts, placed orders, downloaded signed certificates.

I am working on revoking certificates, … but this leads to my question:  **How do you check the revocation status of a certificate?**

I looked at the code in the web-front-end (wfe.go), but it doesn't seem to have any endpoint that looks like checking the revocation status of a certificate.

Any pointers would be appreciated.

**Comment by felixfontein** [comment]
I don't think you can use ACME for this. You can always use OCSP, but that doesn't work for certificates issued by Pebble.

If you just want to make sure that a certificate is revoked, you can simply revoke it; if it already was revoked, Pebble and Boulder will return a nice machine-readable error (`urn:ietf:params:acme:error:alreadyRevoked`; [see here](https://tools.ietf.org/html/draft-ietf-acme-acme-16#page-57)).

**Comment by felixfontein** [comment]
Parallel discussion: https://community.letsencrypt.org/t/how-to-check-revocation-status-of-certificate/78135/5

**Comment by dxjones** [comment]
Since Pebble already keeps track of revoked certificates, it would be useful to be able to query the status of a certificate.  I don't think this would involve much additional code, but it would be one more endpoint.

I realize I could try to revoke a certificate, to find out if it *was* `valid`, `revoked`, (or `uknown`), but that changes the status if the certificate was previously valid.

Would the authors of Pebble be receptive to a new endpoint for checking certificate status?

It would be useful for testing, ... but it would deviate from the approach in Boulder, which uses OCSP for that purpose.

**Comment by osirisinferi** [comment]
As per topic on the community, I don't think an implementation regarding the ACME protocol containing revocation information is the best approach. It also doesn't help your client development: the response of the ACME server when the client tries to revoke a certificate would be enough from an ACME protocol end point.

*However*, when developing a client, one probably would like to have revocation checking, like `certbot` does now when using the `certbot certificates` command. And when one is developing the client with the aid of Pebble, wouldn't it be most logical when Pebble is *also* used for the revocation checking for said client? Because the revoced certificates would be issued by Pebble in the first place.

**Comment by felixfontein** [comment]
> Since Pebble already keeps track of revoked certificates, it would be useful to be able to query the status of a certificate.

Could you please explain *why* it would be useful for testing? What exactly do you want to test? You should provide a good reason why something non-standard (i.e. not mentioned in the ACME drafts/RFCs) should be implemented in Pebble, which is meant as a minimal test CA which implements the ACME protocol.

**Comment by cpu** [comment]
I don't think Pebble should be viewed as a complete simulation of a fully functional CA - its strictly for ACME. I view a fully-fledged OCSP responder as out of scope for Pebble since as mentioned by others it isn't a function of the ACME protocol. Using the OCSP Responder from Boulder will mean pulling in the CFSSL dependency or rewriting a big piece of code. Both seem like big trade-offs for Pebble that I don't think are justified in this case.

I would be open to having a non-standard mechanism for asking Pebble which certificates were revoked but I would want to see it added as a sub-feature of https://github.com/letsencrypt/pebble/issues/74

**Comment by cpu** [comment]
I updated #74 to mention this use-case. PRs welcome!

I'm going to close this issue for the time being to centralize discussion on the HTTP management interface issue. 

Thanks!

**Comment by felixfontein** [comment]
In the meantime, there is an endpoint for checking revocation status of a certificate (via its serial number). It has been implemented in #252 (merged).

Together with #242, one can create a simple OCSP responder which works together with Pebble.

**Comment by liweitianux** [comment]
> In the meantime, there is an endpoint for checking revocation status of a certificate (via its serial number). It has been implemented in #252 (merged).
> 
> Together with #242, one can create a simple OCSP responder which works together with Pebble.

Thank you for the info.  I've created a simple OCSP responder and post it at https://gist.github.com/liweitianux/ceff7dccd308a917e415dadb1c05418c . Hope it could help others :smile:.
