### ISSUE TITLE
simulate Mulit-VA environment

### ISSUE THREAD

**Issue by orangepizza** [letsencrypt/pebble#295]
while it won't be problem for dns or webroot plugin, this can detect some standalone server implementation that only reply once then stops. 
most simple implemantation would call http request X time and compare it in challenge, but would it enough?

**Comment by cpu** [comment]
Hi @orangepizza, thanks for opening an issue.

I think Pebble is already a pretty good simulation of multi-va (minus distinct egress IP addresses for validation requests, the same as Boulder's dev env). 

>  this can detect some standalone server implementation that only reply once then stops. most simple implemantation would call http request X time and compare it in challenge, but would it enough?

That's what Pebble does today :-) It makes 3 validation requests per challenge and **all** of them must pass for the authorization to be valid:
https://github.com/letsencrypt/pebble/blob/295d9c1182f27616cd91770f5e535e85a37e2cb9/va/va.go#L42-L43

By default it also spaces the requests out for a random amount of time up to 5 seconds apart:

https://github.com/letsencrypt/pebble/blob/295d9c1182f27616cd91770f5e535e85a37e2cb9/va/va.go#L58-L61

I'm going to close this issue out since I think the only improvement left to make would be to add multiple source IP addresses and that would require multiple Pebble processes or added complexity in the validation code and I don't think either are a great fit for Pebble.

Thanks again!
