### ISSUE TITLE
How to configure the validity period of the issued certificate?

### ISSUE THREAD

**Issue by jinliming2** [letsencrypt/pebble#319]
In the default configuration, the validity period of the certificate issued by pebble is 5 years, but now I need to test my program to automatically renew the certificate when the certificate is about to expire, so I need to set the validity period of the certificate to a shorter time.

**Comment by aarongable** [comment]
Pebble does not have configuration for certificate lifetime, it is simply hardcoded to 5 years:
https://github.com/letsencrypt/pebble/blob/05f79ba495ab6a27cbbc32e20b44afac52eb9914/ca/ca.go#L233

One common solution in situations like this is to ensure that the system you are testing takes a clock as an input, rather than always independently loading the system clock. Then the tests can provide a fake clock, and control what time the system-under-test believes it is.
