### ISSUE TITLE
Boulder Divergences: Duplicate Orders and Authorizations

### ISSUE THREAD

**Issue by jvanasco** [letsencrypt/pebble#324]
There are several divergences in the behavior of Boulder and Pebble.

Divergence 1- Authorizations

* Account A submits an order for `a.example.com`. No challenge is triggered.
* Account A submits a second order for `a.example.com`

Pebble will generate a Unique Authorization (Unique Authorization URL + Unique Challenges) for each order.
Boulder will use the same Authorization URL + Challenges for both orders.

Divergence 2- Orders

* Account A submits an order for `a.example.com` or `a.example.com+b.example.com`. One challenge is triggered and fails.
* Account A submits a second order for `a.example.com, b.example.com`.

Pebble will generate a Unique Order URL for each order.
Boulder is unpredictable and may re-use the Order URL.  This seems to happen on single domain orders too, but this has been unpredictable in my tests and hard to reproduce.

Just to be clear: I am not making an opinion on the behavior of either server. These are significant divergences, and are not documented. The Pebble documentation teaches away from expecting this, as it only speaks of similar divergences to Boulder in regards to re-using validated authorizations, not pending ones.

Edit: After additional testing, Boulder seems to re-use the Order URL with 'random domains', but not with "known" domains. Either triggering a challenge or touching/deactivating an authorization appears to change something and issue a new order URL.

**Comment by felixfontein** [comment]
Why should that be an issue?

**Comment by jvanasco** [comment]
@felixfontein this submitted by accident, without all the text.  refiling.

**Comment by aarongable** [comment]
Out of curiosity, why are these divergences seen as significant? In what ways would a client's behavior differ based on whether a given authorization or order object was re-used?

Interestingly, re-use of these objects is neither specifically allowed nor specifically forbidden by the ACME spec. Where possible, I'd suggest that clients always behave as though a received authorization or order object is brand new.

**Comment by jvanasco** [comment]
> Where possible, I'd suggest that clients always behave as though a received authorization or order object is brand new.

That is exactly what I did with the Order, and what caused our problem.  The correct assumption is to behave as if anything might reused.  Lesson learned!

> Interestingly, re-use of these objects is neither specifically allowed nor specifically forbidden by the ACME spec.

The ACME spec is vague on a lot of things, which is why it is important for related projects - such as Boulder and Pebble - to document their divergences in implementing it against one another.  It is likewise important document what a "strict" interpretation of a specification elements exactly is when those decisions are made. The RFC defines a Protocol which addresses Servers and Clients, but the developers of a Server and a Client will often have incompatible definitions of what a strict interpretation of a given clause is. This has been the cause of a few issues on this project before; e.g. a "strict" interpretation to one audience may mean a mutually exclusive A or B, and to another audience it means A or B or A+B.

The only mention of reusing objects within this project is in regards to validated authorizations, such as the text "ACME servers may choose to reuse valid authorizations from previous orders" and the flag `PEBBLE_AUTHZREUSE`.  Presenting information in this manner effectively teaches away from the fact "ACME servers may choose to reuse VALID OR PENDING authorizations from previous orders".  

> Out of curiosity, why are these divergences seen as significant? In what ways would a client's behavior differ based on whether a given authorization or order object was re-used?

A client's behavior should not differ as to interactions with the ACME Server and order processing.  The internal operations of a client are a different matter.  In my situation, our client was broken against Boulder, because we store ACME data in a relational database. A database is used because our client is mostly API driven and responds to automated systems instead of invoking them (like Certbot) so it: (i) must persist data across processes and (ii) have information easily searchable for reports and auditing.  The fix was a few lines to check if a new Order object needed to be created or not; the Authorizations were already handled properly, in case previously validated authorizations ever appeared in an AcmeOrder payload.  Thankfully, we had no issues in production from this.

Again, I really need to stress this point: I am not advocating for changes to the behavior or implementation, only that differences like this be properly documented. If a design decision is made my a maintainer/contributor as to how something in the RFC should be implemented, it should be recognized as an indicator that documentation is merited that simply notes their decision. 

It would be useful if there were a percentage flag to adjust these behaviors, like `PEBBLE_AUTHZREUSE` but I don't have time to generate a PR myself and few clients preserve state or track history like mine.  

As-is, Pebble isn't a suitable replacement against Boulder for testing or Development as previously advertised. There have been too many undocumented differences and the staging API is a better server.  Pebble's utility is more suited as an alternate RFC implementation that can be used for stress benching fully functional clients.

**Comment by aarongable** [comment]
Ok, the persistence here is the piece I was missing. As you're aware, most clients just keep their records of orders and authorizations in-memory, and have no reason to care if a given order ID is reused between runs.

Boulder tries to return pre-existing orders because doing so allows clients to recover from client-side failures without exceeding the newOrder rate limits: if there's already an existing order in the Pending or Ready state, returning that one keeps the client happy (no rate limits), and keeps our database happy (no new inserts).

Pebble doesn't bother trying to do that because pebble doesn't have any rate limits.

On the one hand, we try to have Pebble be _more_ dangerous than Boulder, both so that people don't rely on it for production use, and so that any client which can reliably work with pebble can also reliably work with boulder. You're right that, in this case, the discrepancy seems to go the wrong direction.

On the other hand, we also try to have Pebble be _simpler_ than Boulder, because we don't have the time to make it exhibit every single corner-case behavior Boulder has.

If you can, please file a PR to update the README to include mention of this lack of re-use. Once you do, I'll update this issue to be a feature request for randomized order and pending authorization reuse. Thanks!

**Comment by jvanasco** [comment]
@aarongable Sure, filed.  The Persistence aspect is definitely the outlier in terms of functionality.  We encountered so many issues when trying to troubleshoot from "logs", that it became one of the main reasons to make a client.

**Comment by jvanasco** [comment]
Here's a related question that could impact the PR: could/would Challenges be re-used?

The RFC doesn't explicitly state they can't be re-used in anything I've read. No ACME server I've seen does this, but let's look at the RFC:

* Explicit: A "valid" Challenge remains on a "valid" Authorization; an "invalid" Challenge remains on an "invalid" Authorization; the Authorizations remain on the Order.
* Implied: A "pending" Challenge can't be associated to more than one "pending" Authorization.

With this understanding, the pool of potentially reusable objects are the non-triggered Challenges from non-pending Authorizations. That is a very large pool of objects, but the logic is complex enough that it's not really worth pursuing... and no Acme server *would* recycle them.  In terms of *could*, is there anything in the RFC that I've missed which would prohibit ACME servers from re-using it?

**Comment by jsha** [comment]
Good point! Yes, I believe Challenges could be reused according to the spec. Note that a CA would have to be very careful in implementing this, for a variety of reasons. For instance, the DNS name information is notionally attached to the Authorization, not the challenge, so the CA would have to ensure it had an internal association for the DNS name.

Boulder's very unlikely to implement Challenge reuse separately from Authorization reuse, because we treat Challenges as fundamentally a part of Authorizations - there's one row in the DB for an Authorization, and that also includes the information for all of that Authorization's challenges.

**Comment by jvanasco** [comment]
I'm closing this as https://github.com/letsencrypt/boulder/pull/5105 essentially addresses this.
