### ISSUE TITLE
Allow changing the ToS

### ISSUE THREAD

**Issue by danimo** [letsencrypt/pebble#327]
Currently, the ToS is hardcoded to a static string and not configurable through the config file:

https://github.com/letsencrypt/pebble/blob/master/wfe/wfe.go#L160

 This means it's impossible to use pebble to validate clients against [section 7.3.3](https://tools.ietf.org/html/rfc8555#section-7.3.3). I am not sure if LE intents to support this or if boulder does for that matter.

**Comment by aarongable** [comment]
The pebble terms of service ("Do what thou wilt") will never change; pebble is not intended to be a production service for anyone, and will never be a service which ISRG / Let's Encrypt runs.

The boulder terms of service can and do change, but they change without requiring subscribers to reset the `termsOfServiceAgreed` bit on their account object. See the [current terms of service](https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf), Section 5.6 "Amendment".

However, even if boulder and/or pebble did require subscribers to agree to new terms of service, note that an ACME client _cannot_ automatically do so:

RFC 8555 s7.1.2 Account Objects:
>  termsOfServiceAgreed (optional, boolean):... This field cannot be updated by the client.

RFC 8555 s7.3.2 Account Update:
> The server MUST ignore any updates to the... "termsOfServiceAgreed" field (see Section 7.3.3)...

RFC 8555 s7.3.3 Changes of Terms of Service:
> The problem document returned with the error MUST also include an "instance" field, indicating a URL that the client should _direct a human user to visit_ in order for instructions on how to agree to the terms.

(emphasis mine)

Because the whole point of ACME is to not require user intervention, and there is no clear standard for how an acme client would communicate such a thing with the human it represents (let alone how it would do so synchronously, while trying to place a new order), boulder [does not intend to ever serve the userActionRequired error code](https://github.com/letsencrypt/boulder/search?q=userActionRequired). Pebble follows suit.

**Comment by danimo** [comment]
The original intent behind my question was to test showing the error plus the actionable link, and being able to test that, for dehydrated. We'll wait for a suitable and validateable use  in others CAs then I guess :)
