### ISSUE TITLE
Feature Request - Random Account URLs

### ISSUE THREAD

**Issue by jvanasco** [letsencrypt/pebble#340]
The account URLs appear to be sequential based.  It would be useful if the urls were randomized, or potentially randomized by an environment variable.  Alternatively, the URLs could contain a hash of the contact email address.  (These are just the two simplest ideas i had)

     -  https://0.0.0.0:14000/my-account/1
     +  https://0.0.0.0:14000/my-account/c556d4  # where `c556d4` is random

or 

     -  https://0.0.0.0:14000/my-account/1
     +  https://0.0.0.0:14000/my-account/1/7fc31f   # where `7fc31f` is a hash of the contact

Use Case:

Our test systems typically use an isolated pebble server per test suite in an attempt to try and break things, then reconcile data with the server if possible or handle "this is broken!".  This works perfectly, except for accounts.

When restarting the pebble server, the first account is always "https://0.0.0.0:14000/my-account/1". This creates an issue as, in the context of a pebble test server, this URL represents a uniquely new account -- but in the context of a production boulder server with persistent storage, this url represents an existing account that needs to be reconciled on our end.

While a workaround is to alter the database items after tests, this is less than ideal.

**Comment by jsha** [comment]
I like this idea!

**Comment by squizzling** [comment]
I'm taking a look at this.  The approach I'm leaning towards is taking a hash of all the contact emails on creation, the potential hazard I see is updating the account contacts would then put them out of sync.  I don't think this actually matters though, since (if I understand correctly) it's just a source of pseudo-entropy for the initial id, but is this assumption valid?

I'm also not sure how consistent the account ID should be overall.  If it's a hash of contacts, then it's consistent across runs but can still conflict (although you could use a new contact address per test).  If it's purely random then there's guaranteed no conflict.

All are fairly easy to do, and making it configurable would also be an option (including an option for legacy behavior), I just need to know the preferred direction.

**Comment by aarongable** [comment]
I'd lean towards truly-random, rather than hash of the contacts. Tests can certainly benefit from predictable behavior in the "mock" that they're testing against, but I believe they benefit _more_ from the mocks behaving as realistically as possible -- and in Boulder, account IDs are not predictable. I think the solution here is to just create a math.rand, seed it with the current time, and use that to generate account ID integers.

Pebble makes no guarantees about account IDs, so this shouldn't require a feature flag IMO, but it will prompt a minor version bump (v2.4.0) when released.
