### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by ChristianKoehler** [letsencrypt/pebble#369]
Hi,
I would love to see https://github.com/letsencrypt/pebble/pull/361 in the official docker image to get rid of the `NET::ERR_CERT_VALIDITY_TOO_LONG` errors in Chrome. It might be necessary to update the Dockerfiles to use go 1.16 as the builder images.

Thanks!

**Comment by aaomidi** [comment]
Bump on this a new release of pebble would be great so we can test notAfter functionality in certbot

**Comment by osirisinferi** [comment]
@aaomidi This issue is for a release including a *configuration option* regarding certificate lifetime, not the `notBefore` and `notAfter` ACME fields. That was already merged in Pebble 2.3.1 which was released back in 2020 I believe. [Recently (i.e.: 2 days ago)](https://github.com/certbot/certbot/pull/9260), Certbot has updated its Pebble version for the CI to 2.3.1, so your PR should be good to go. (Please check this just to be sure!)

**Comment by aaomidi** [comment]
Yeep, I misread what the commit was - thank you! Still, a new release would be nice :)

**Comment by jsha** [comment]
I've published a new tag: v2.4.0.

We have some infrastructure to automatically create "GitHub Release" from a tag, and attach artifacts: #240. However, it doesn't seem to have fired in this case. We should probably update the Travis-based infrastructure to GHA, and evaluate if we still need AppVeyor. But considering this ticket finished.

**Comment by shred** [comment]
Maybe I'm too impatient, but there is no update on Docker Hub yet.

**Comment by jsha** [comment]
@shred the Docker Hub releases are also part of the automatic release infrastructure that still needs some tending to, so they won't be ready until we fix that.
