### ISSUE TITLE
Update README now that chisel2 is in Boulder repo

### ISSUE THREAD

**Issue by webprofusion-chrisc** [letsencrypt/pebble#44]
Currently the README mention using chisel2 to test pebble (btw, pebble now runs on windows using the latest Bash on Ubuntu for Windows). 

The chisel2.py file no longer seems to be part of the certbot acme-v2 branch, it may be renamed or removed?

**Comment by cpu** [comment]
Hi @webprofusion-chrisc,

Apologies - [pwe moved `chisel2.py` into the Boulder repo](https://github.com/letsencrypt/boulder/commit/e2cc6fbe682dd5d49da32c2357838b0cc831f10f) instead of being in a branch on Certbot but forgot to update the Pebble readme.

We also changed [the default `DIRECTORY`](https://github.com/letsencrypt/boulder/blob/bf9ce64aca5ce9efcf987d56fbfd412d6650cc57/test/chisel2.py#L38) to match the Boulder WFE2 port, which means you'll have to specify a different `DIRECTORY` env var to match Pebble's port. I will update the README accordingly. Thanks for opening an issue!
