### ISSUE TITLE
Failed authorization procedure. beta.aaa.cn (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout

### ISSUE THREAD

**Issue by SirBlues** [letsencrypt/pebble#89]
why
log:
ERROR:certbot.log:An unexpected error occurred:
ERROR:certbot.log:The request message was malformed :: Error creating new authz :: Invalid character in DNS name
Connection: close

{
  "type": "urn:acme:error:malformed",
  "detail": "Error creating new authz :: Invalid character in DNS name",
  "status": 400
}

**Comment by cpu** [comment]
@SirBlues - Your logs show output from Certbot, which is an ACME v1 client not compatible with Pebble and ACMEv2. I'm going to close this issue for now since it isn't a bug in Pebble.

If you are using an ACME v2 client and still get this error please create a new issue and share:
1) What ACME client you're using, and what version
2) How you're running it, any arguments, etc

Thanks!
